"""Static GRE-style seed question data."""

SEED_QUESTIONS = [
    {
        "question_id": "alg-001",
        "prompt": "If 3x + 5 = 20, what is the value of x?",
        "choices": [
            {"key": "A", "text": "3"},
            {"key": "B", "text": "5"},
            {"key": "C", "text": "10"},
            {"key": "D", "text": "15"},
        ],
        "correct_answer": "B",
        "topic": "Algebra",
        "tags": ["linear-equation", "foundations"],
        "difficulty": 0.2,
        "explanation": "Subtract 5 from both sides and divide by 3.",
    },
    {
        "question_id": "alg-002",
        "prompt": "If 2^(x) = 32, what is x?",
        "choices": [
            {"key": "A", "text": "4"},
            {"key": "B", "text": "5"},
            {"key": "C", "text": "6"},
            {"key": "D", "text": "8"},
        ],
        "correct_answer": "B",
        "topic": "Algebra",
        "tags": ["exponents"],
        "difficulty": 0.3,
    },
    {
        "question_id": "alg-003",
        "prompt": "If x^2 - 9 = 0, which of the following could be x?",
        "choices": [
            {"key": "A", "text": "Only 9"},
            {"key": "B", "text": "Only -9"},
            {"key": "C", "text": "3 or -3"},
            {"key": "D", "text": "9 or -9"},
        ],
        "correct_answer": "C",
        "topic": "Algebra",
        "tags": ["quadratics"],
        "difficulty": 0.4,
    },
    {
        "question_id": "alg-004",
        "prompt": "A sequence is defined by a_n = 3n + 2. What is a_7?",
        "choices": [
            {"key": "A", "text": "20"},
            {"key": "B", "text": "21"},
            {"key": "C", "text": "23"},
            {"key": "D", "text": "24"},
        ],
        "correct_answer": "C",
        "topic": "Algebra",
        "tags": ["sequences"],
        "difficulty": 0.45,
    },
    {
        "question_id": "geo-001",
        "prompt": "What is the area of a rectangle with length 8 and width 3?",
        "choices": [
            {"key": "A", "text": "11"},
            {"key": "B", "text": "24"},
            {"key": "C", "text": "16"},
            {"key": "D", "text": "48"},
        ],
        "correct_answer": "B",
        "topic": "Geometry",
        "tags": ["area", "rectangles"],
        "difficulty": 0.2,
    },
    {
        "question_id": "geo-002",
        "prompt": "The circumference of a circle is 10π. What is its radius?",
        "choices": [
            {"key": "A", "text": "5"},
            {"key": "B", "text": "10"},
            {"key": "C", "text": "20"},
            {"key": "D", "text": "25"},
        ],
        "correct_answer": "A",
        "topic": "Geometry",
        "tags": ["circles", "circumference"],
        "difficulty": 0.35,
    },
    {
        "question_id": "geo-003",
        "prompt": "In a right triangle, if the legs are 6 and 8, what is the hypotenuse?",
        "choices": [
            {"key": "A", "text": "10"},
            {"key": "B", "text": "12"},
            {"key": "C", "text": "14"},
            {"key": "D", "text": "16"},
        ],
        "correct_answer": "A",
        "topic": "Geometry",
        "tags": ["triangles", "pythagorean-theorem"],
        "difficulty": 0.4,
    },
    {
        "question_id": "geo-004",
        "prompt": "A cylinder has radius 2 and height 5. What is its volume?",
        "choices": [
            {"key": "A", "text": "10π"},
            {"key": "B", "text": "20π"},
            {"key": "C", "text": "25π"},
            {"key": "D", "text": "40π"},
        ],
        "correct_answer": "B",
        "topic": "Geometry",
        "tags": ["volume", "solids"],
        "difficulty": 0.55,
    },
    {
        "question_id": "vocab-001",
        "prompt": "Select the word that is closest in meaning to 'abate'.",
        "choices": [
            {"key": "A", "text": "Increase"},
            {"key": "B", "text": "Endure"},
            {"key": "C", "text": "Lessen"},
            {"key": "D", "text": "Predict"},
        ],
        "correct_answer": "C",
        "topic": "Vocabulary",
        "tags": ["synonyms"],
        "difficulty": 0.25,
    },
    {
        "question_id": "vocab-002",
        "prompt": "Select the word that is opposite in meaning to 'lucid'.",
        "choices": [
            {"key": "A", "text": "Clear"},
            {"key": "B", "text": "Obscure"},
            {"key": "C", "text": "Detailed"},
            {"key": "D", "text": "Polished"},
        ],
        "correct_answer": "B",
        "topic": "Vocabulary",
        "tags": ["antonyms"],
        "difficulty": 0.35,
    },
    {
        "question_id": "vocab-003",
        "prompt": "In the sentence 'Her comments were entirely pragmatic,' the word 'pragmatic' most nearly means:",
        "choices": [
            {"key": "A", "text": "Idealistic"},
            {"key": "B", "text": "Practical"},
            {"key": "C", "text": "Emotional"},
            {"key": "D", "text": "Uncertain"},
        ],
        "correct_answer": "B",
        "topic": "Vocabulary",
        "tags": ["contextual-meaning"],
        "difficulty": 0.4,
    },
    {
        "question_id": "vocab-004",
        "prompt": "Select the best meaning of 'equivocal'.",
        "choices": [
            {"key": "A", "text": "Unambiguous"},
            {"key": "B", "text": "Open to multiple interpretations"},
            {"key": "C", "text": "Hostile"},
            {"key": "D", "text": "Highly praised"},
        ],
        "correct_answer": "B",
        "topic": "Vocabulary",
        "tags": ["advanced-vocabulary"],
        "difficulty": 0.6,
    },
    {
        "question_id": "rc-001",
        "prompt": "A passage argues that urban parks improve public health by encouraging exercise. Which statement is best supported?",
        "choices": [
            {"key": "A", "text": "Urban parks reduce the need for hospitals."},
            {"key": "B", "text": "Access to parks may increase physical activity."},
            {"key": "C", "text": "Only cities benefit from public spaces."},
            {"key": "D", "text": "Exercise is impossible without parks."},
        ],
        "correct_answer": "B",
        "topic": "Reading Comprehension",
        "tags": ["inference"],
        "difficulty": 0.3,
    },
    {
        "question_id": "rc-002",
        "prompt": "If an author presents two theories and then provides evidence favoring the second, the primary purpose is most likely to:",
        "choices": [
            {"key": "A", "text": "Dismiss both theories equally"},
            {"key": "B", "text": "Show that all evidence is inconclusive"},
            {"key": "C", "text": "Argue that the second theory is stronger"},
            {"key": "D", "text": "Avoid taking a position"},
        ],
        "correct_answer": "C",
        "topic": "Reading Comprehension",
        "tags": ["author-purpose"],
        "difficulty": 0.45,
    },
    {
        "question_id": "rc-003",
        "prompt": "A paragraph contrasts short-term cost with long-term benefit. The contrast primarily serves to:",
        "choices": [
            {"key": "A", "text": "Undermine the idea of planning"},
            {"key": "B", "text": "Highlight a tradeoff in decision-making"},
            {"key": "C", "text": "Demonstrate a contradiction in the data"},
            {"key": "D", "text": "Prove that costs always exceed benefits"},
        ],
        "correct_answer": "B",
        "topic": "Reading Comprehension",
        "tags": ["reasoning", "structure"],
        "difficulty": 0.5,
    },
    {
        "question_id": "rc-004",
        "prompt": "An author uses the phrase 'a narrow lens' to criticize an argument. This phrase most nearly suggests the argument is:",
        "choices": [
            {"key": "A", "text": "Too broad"},
            {"key": "B", "text": "Insufficiently comprehensive"},
            {"key": "C", "text": "Scientifically rigorous"},
            {"key": "D", "text": "Historically inaccurate"},
        ],
        "correct_answer": "B",
        "topic": "Reading Comprehension",
        "tags": ["tone", "interpretation"],
        "difficulty": 0.55,
    },
    {
        "question_id": "data-001",
        "prompt": "The mean of five numbers is 12. What is their total sum?",
        "choices": [
            {"key": "A", "text": "17"},
            {"key": "B", "text": "48"},
            {"key": "C", "text": "60"},
            {"key": "D", "text": "72"},
        ],
        "correct_answer": "C",
        "topic": "Data Analysis",
        "tags": ["mean"],
        "difficulty": 0.25,
    },
    {
        "question_id": "data-002",
        "prompt": "A bag contains 4 red and 6 blue marbles. What is the probability of drawing a red marble?",
        "choices": [
            {"key": "A", "text": "1/10"},
            {"key": "B", "text": "2/5"},
            {"key": "C", "text": "3/5"},
            {"key": "D", "text": "4/5"},
        ],
        "correct_answer": "B",
        "topic": "Data Analysis",
        "tags": ["probability"],
        "difficulty": 0.35,
    },
    {
        "question_id": "data-003",
        "prompt": "If the median of the set {2, 4, 7, 9, x} is 7, which of the following could be x?",
        "choices": [
            {"key": "A", "text": "1"},
            {"key": "B", "text": "7"},
            {"key": "C", "text": "12"},
            {"key": "D", "text": "Both B and C"},
        ],
        "correct_answer": "D",
        "topic": "Data Analysis",
        "tags": ["median"],
        "difficulty": 0.5,
    },
    {
        "question_id": "data-004",
        "prompt": "A study reports that 60% of 250 surveyed students prefer digital notes. How many students is that?",
        "choices": [
            {"key": "A", "text": "100"},
            {"key": "B", "text": "125"},
            {"key": "C", "text": "150"},
            {"key": "D", "text": "175"},
        ],
        "correct_answer": "C",
        "topic": "Data Analysis",
        "tags": ["percentages"],
        "difficulty": 0.3,
    },
    {
        "question_id": "alg-005",
        "prompt": "If f(x) = 2x^2 - 3x + 1, what is f(2)?",
        "choices": [
            {"key": "A", "text": "1"},
            {"key": "B", "text": "3"},
            {"key": "C", "text": "5"},
            {"key": "D", "text": "7"},
        ],
        "correct_answer": "B",
        "topic": "Algebra",
        "tags": ["functions"],
        "difficulty": 0.55,
    },
    {
        "question_id": "geo-005",
        "prompt": "Two similar triangles have corresponding side lengths in the ratio 2:5. If the smaller triangle has area 12, what is the area of the larger?",
        "choices": [
            {"key": "A", "text": "30"},
            {"key": "B", "text": "60"},
            {"key": "C", "text": "75"},
            {"key": "D", "text": "90"},
        ],
        "correct_answer": "C",
        "topic": "Geometry",
        "tags": ["similarity", "area"],
        "difficulty": 0.7,
    },
    {
        "question_id": "vocab-005",
        "prompt": "Select the word that best completes the sentence: 'Because the evidence was ___, the committee postponed its decision.'",
        "choices": [
            {"key": "A", "text": "conclusive"},
            {"key": "B", "text": "equivocal"},
            {"key": "C", "text": "abundant"},
            {"key": "D", "text": "precise"},
        ],
        "correct_answer": "B",
        "topic": "Vocabulary",
        "tags": ["sentence-equivalence"],
        "difficulty": 0.65,
    },
    {
        "question_id": "rc-005",
        "prompt": "A passage claims that technological progress is uneven across industries. Which example would best strengthen that claim?",
        "choices": [
            {"key": "A", "text": "All industries adopt innovation at the same rate."},
            {"key": "B", "text": "Healthcare digitization lags while finance automates rapidly."},
            {"key": "C", "text": "Most companies use computers."},
            {"key": "D", "text": "Consumers prefer modern products."},
        ],
        "correct_answer": "B",
        "topic": "Reading Comprehension",
        "tags": ["strengthen-argument"],
        "difficulty": 0.65,
    },
    {
        "question_id": "data-005",
        "prompt": "An investment grows by 10% in year one and then falls by 10% in year two. Compared with the original amount, the final amount is:",
        "choices": [
            {"key": "A", "text": "Higher by 1%"},
            {"key": "B", "text": "The same"},
            {"key": "C", "text": "Lower by 1%"},
            {"key": "D", "text": "Lower by 10%"},
        ],
        "correct_answer": "C",
        "topic": "Data Analysis",
        "tags": ["percent-change"],
        "difficulty": 0.6,
    },
]
